"use client";

import React from "react";
import ExpandSearchComponent from "@/components/ExpandSearchComponent";
import AgGridTableComponent from "@/components/AgGridTableComponent";

export default function ComplianceCertificate() {
  const customColumns = [
    { headerName: "Certificate ID", field: "id" },
    { headerName: "Generated By", field: "generated_by" },
    { headerName: "Generated Date", field: "generated_date" },
    { headerName: "Certificate", field: "certificate", islink: true },
    { headerName: "From", field: "from" },
    { headerName: "To", field: "to" },
  ];
  const staticData = [
    {
      id: 1,
      generated_by: "Compliance Tool User",
      generated_date: "06-04-2023",
      from: "01-02-2023",
      to: "06-04-2023",
      certificate: "certificate_sample.pdf",
    },
    {
      id: 2,
      generated_by: "Compliance Tool User",
      generated_date: "06-04-2023",
      from: "01-02-2023",
      to: "06-04-2023",
      certificate: "certificate_sample.pdf",
    },
    {
      id: 3,
      generated_by: "Compliance Tool User",
      generated_date: "06-04-2023",
      from: "01-02-2023",
      to: "06-04-2023",
      certificate: "certificate_sample.pdf",
    },
    {
      id: 4,
      generated_by: "Compliance Tool User",
      generated_date: "06-04-2023",
      from: "01-02-2023",
      to: "06-04-2023",
      certificate: "certificate_sample.pdf",
    },
    {
      id: 5,
      generated_by: "Compliance Tool User",
      generated_date: "06-04-2023",
      from: "01-02-2023",
      to: "06-04-2023",
      certificate: "certificate_sample.pdf",
    },
    {
      id: 6,
      generated_by: "Compliance Tool User",
      generated_date: "06-04-2023",
      from: "01-02-2023",
      to: "06-04-2023",
      certificate: "certificate_sample.pdf",
    },
    {
      id: 7,
      generated_by: "Compliance Tool User",
      generated_date: "06-04-2023",
      from: "01-02-2023",
      to: "06-04-2023",
      certificate: "certificate_sample.pdf",
    },
    {
      id: 8,
      generated_by: "Compliance Tool User",
      generated_date: "06-04-2023",
      from: "01-02-2023",
      to: "06-04-2023",
      certificate: "certificate_sample.pdf",
    },
    {
      id: 9,
      generated_by: "Compliance Tool User",
      generated_date: "06-04-2023",
      from: "01-02-2023",
      to: "06-04-2023",
      certificate: "certificate_sample.pdf",
    },
    {
      id: 10,
      generated_by: "Compliance Tool User",
      generated_date: "06-04-2023",
      from: "01-02-2023",
      to: "06-04-2023",
      certificate: "certificate_sample.pdf",
    },
    {
      id: 11,
      generated_by: "Compliance Tool User",
      generated_date: "06-04-2023",
      from: "01-02-2023",
      to: "06-04-2023",
      certificate: "certificate_sample.pdf",
    },
    {
      id: 12,
      generated_by: "Compliance Tool User",
      generated_date: "06-04-2023",
      from: "01-02-2023",
      to: "06-04-2023",
      certificate: "certificate_sample.pdf",
    },
  ];

  const formFields = [
    {
      label: "From Date",
      name: "from_date",
      type: "date",
      required: false,
    },
    {
      label: "To Date",
      name: "to_date",
      type: "date",
      required: false,
    },
  ];

  return (
    <div>
      <ExpandSearchComponent
        slug="/compliance-certificates"
        page="Filter Compliance Certificate"
        buttonName="Filter"
        formFields={formFields}
      />
      <AgGridTableComponent
        slug="/compliance-certificates"
        page="Certificate List"
        customColumns={customColumns}
        customRows={staticData}
      />
    </div>
  );
}
