import * as z from "zod"
import { frequency, imprisonment_for, impact, impact, impact } from "@prisma/client"

export const client_activityModel = z.object({
  id: z.number().int().nullish(),
  uuid: z.string().nullish(),
  activity_code: z.string(),
  title: z.string().nullish(),
  legislation: z.string(),
  rule: z.string(),
  reference: z.string(),
  who: z.string(),
  when: z.string(),
  activity: z.string(),
  procedure: z.string(),
  description: z.string().nullish(),
  frequency: z.nativeEnum(frequency).nullish(),
  form_no: z.string().nullish(),
  compliance_type: z.string().nullish(),
  authority: z.string().nullish(),
  exemption_criteria: z.string().nullish(),
  event: z.string().nullish(),
  event_sub: z.string().nullish(),
  event_question: z.string().nullish(),
  implications: z.string().nullish(),
  imprison_duration: z.string().nullish(),
  imprison_applies_to: z.nativeEnum(imprisonment_for).nullish(),
  currency: z.string().nullish(),
  fine: z.string().nullish(),
  fine_per_day: z.string().nullish(),
  impact: z.nativeEnum(impact),
  impact_on_unit: z.nativeEnum(impact).nullish(),
  impact_on_organization: z.nativeEnum(impact).nullish(),
  linked_activity_ids: z.string().nullish(),
  reference_link: z.string().nullish(),
  sources: z.string().nullish(),
  documents: z.string().nullish(),
  status: z.number().int().nullish(),
  created_at: z.date().nullish(),
  updated_at: z.date().nullish(),
  deleted_at: z.date().nullish(),
  deleted: z.boolean().nullish(),
})
