import * as z from "zod"
import { frequency, imprisonment_for, impact } from "@prisma/client"

export const compliance_activityModel = z.object({
  id: z.number().int().nullish(),
  uuid: z.string().nullish(),
  legislation_id: z.number().int().nullish(),
  rule_id: z.number().int().nullish(),
  code: z.string().nullish(),
  title: z.string(),
  activity: z.string(),
  reference: z.string().nullish(),
  who: z.string().nullish(),
  when: z.string().nullish(),
  procedure: z.string().nullish(),
  description: z.string().nullish(),
  frequency: z.nativeEnum(frequency).nullish(),
  form_no: z.string().nullish(),
  due_date: z.date().nullish(),
  compliance_type: z.string().nullish(),
  authority: z.string().nullish(),
  exemption_criteria: z.string().nullish(),
  event_id: z.number().int().nullish(),
  event_sub_id: z.number().int().nullish(),
  event_question_id: z.number().int().nullish(),
  implications: z.string().nullish(),
  imprison_duration: z.string().nullish(),
  imprison_applies_to: z.nativeEnum(imprisonment_for).nullish(),
  currency: z.string().nullish(),
  fine: z.string().nullish(),
  fine_per_day: z.string().nullish(),
  impact: z.nativeEnum(impact).nullish(),
  impact_on_unit: z.string().nullish(),
  impact_on_organization: z.string().nullish(),
  linked_activity_ids: z.string().nullish(),
  reference_link: z.string().nullish(),
  sources: z.string().nullish(),
  updated_date: z.date().nullish(),
  documents: z.string().nullish(),
  status: z.number().int().nullish(),
  created_at: z.date().nullish(),
  deleted_at: z.date().nullish(),
  deleted: z.boolean().nullish(),
  updated_at: z.date().nullish(),
})
